name: MusicPlayer
options:
  bundleIdPrefix: com.zkk
  deploymentTarget:
    iOS: "17.0"
  xcodeVersion: "15.0"
  generateEmptyDirectories: true

settings:
  base:
    SWIFT_VERSION: "5.9"
    DEVELOPMENT_TEAM: ""
    CODE_SIGN_STYLE: Automatic
    INFOPLIST_FILE: MusicPlayer/Info.plist

targets:
  MusicPlayer:
    type: application
    platform: iOS
    sources:
      - path: MusicPlayer
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.zkk.musicplayer
        INFOPLIST_FILE: MusicPlayer/Info.plist
        CODE_SIGN_ENTITLEMENTS: MusicPlayer/MusicPlayer.entitlements
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        TARGETED_DEVICE_FAMILY: "1,2"
    entitlements:
      path: MusicPlayer/MusicPlayer.entitlements
      properties:
        com.apple.security.application-groups:
          - group.com.zkk.musicplayer
